# This file was generated by GoReleaser. DO NOT EDIT.
cask "spoo" do
  version "0.1.2"

  on_macos do
    on_intel do
      sha256 "e3be2cbb1ad554bb0c24d48c520e66d9c0913c22ea519fac2c884f95661815c4"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c58623d8432b9b122e6c696c1f853affa0dc3ee2c5ee17c5f6f873898566cc74"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "eb961761a85d616b4fbdf25bc88c9242948420db93e2341c88be3df441474a95"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "68c9c85db2b2717db1dd9a3b69ce754c82df51b191f5466a03ff681e4ee7f12c"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spoo"
  desc "The official command-line client for spoo.me"
  homepage "https://spoo.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spoo"

  # No zap stanza required

end
