# This file was generated by GoReleaser. DO NOT EDIT.
cask "spoo" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "2dbce4d70d8bce4d390b2fae1ad262a85a53a8912b8b4037337a75d86fe5a963"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "6b19e67d83e7bcc5e3c9a065beef2c35c4c5b1b63afb99d71908e6e75fbb78e2"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "10a1cb225371072b9e977c89c06e6865b88ee931c6979950a49ad4e41f245270"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "0b6d8de63eb7cf0bd8f31d8153ee5ad686da02bd23fd9cd610779c73b3cb763c"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spoo"
  desc "The official command-line client for spoo.me"
  homepage "https://spoo.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spoo"

  # No zap stanza required

end
