# This file was generated by GoReleaser. DO NOT EDIT.
cask "spoo" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "9c98dd08353ce5dbcefbf1152ed93e6b4fed0edba14be7969fbea10f4c0564a1"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "96799c0385fe29239be899916d89c7d44100f238d9d74d6dbd03dc68dfcd3c58"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "9425858977af132fe5785ade39fffea29e0514b11dfc9f9606b9724242986b97"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "47c4bc0c0721bd44f55b8941d358903bb6d159c948edd40ad76ee0ea0f17edf8"
      url "https://github.com/spoo-me/spoo-cli/releases/download/v#{version}/spoo_#{version}_linux_arm64.tar.gz"
    end
  end

  name "spoo"
  desc "The official command-line client for spoo.me"
  homepage "https://spoo.me"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "spoo"

  # No zap stanza required

end
